services:
  mysql-db:
    build:
      context: ./mysql
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  memcached:
    image: memcached:1.6
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
  
  web-app:
    build:
      context: ./app
    container_name: web-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - memcached
      - rabbitmq
    networks:
      - backend

  nginx-proxy:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-app
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
